var map_config = {
	'default':{
		'borderColor':'#9CA8B6', //region outlines
		'mapShadow':'#000', //shadow color below the map
		'shadowOpacity':'50', //shadow opacity, value, 0-100
	},
	'map_1':{
		'hover': 'ANDHRA PRADESH',  //region hover content
		'url':'http://localhost/wikilogy/mpdata.php?q=Andhra_Pradesh&id=1', //Goto URL
		'target':'same_window', //open link in new window:new_window, open in current window:same_window, or none for nothing.
		'upColor':'#EBECED', //region color when page loads
		'overColor':'#FFEE88', //region color when mouse hover
		'downColor':'#993366',//region color when mouse clicking
		'enable':true,//true/false to enable/disable this region
	},
	'map_2':{
		'hover': 'ARUNACHAL PRADESH',
		'url':'http://localhost/wikilogy/mpdata.php?q=arunachal%20pradesh&id=2',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_3':{
		'hover': 'ASSAM',
		'url':'http://localhost/wikilogy/mpdata.php?q=asssam&id=3',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_4':{
		'hover': 'BIHAR',
		'url':'http://localhost/wikilogy/mpdata.php?q=bihar&id=4',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_5':{
		'hover': 'CHHATTISGARH',
		'url':'http://localhost/wikilogy/mpdata.php?q=chhattisgarh&id=5',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_6':{
		'hover': 'GOA',
		'url':'http://localhost/wikilogy/mpdata.php?q=goa&id=6',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_7':{
		'hover': 'GUJARAT',
		'url':'http://localhost/wikilogy/mpdata.php?q=gujarat&id=7',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_8':{
		'hover': 'HARYANA',
		'url':'http://localhost/wikilogy/mpdata.php?q=haryana&id=8',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_9':{
		'hover': 'HIMACHAL PRADESH',
		'url':'http://localhost/wikilogy/mpdata.php?q=himachal%20pradesh&id=9',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_10':{
		'hover': 'JAMMU AND KASHMIR',
		'url':'http://localhost/wikilogy/mpdata.php?q=jammu_and_kashmir&id=10',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_11':{
		'hover': 'JHARKHAND',
		'url':'http://localhost/wikilogy/mpdata.php?q=jharkhand&id=11',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_12':{
		'hover': 'KARNATAKA',
		'url':'http://localhost/wikilogy/mpdata.php?q=karnataka&id=12',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_13':{
		'hover': 'KERALA',
		'url':'http://localhost/wikilogy/mpdata.php?q=kerala&id=13',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_14':{
		'hover': 'MADHYA PRADESH',
		'url':'http://localhost/wikilogy/mpdata.php?q=madhya%20pradesh&id=14',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_15':{
		'hover': 'MAHARASHTRA',
		'url':'http://localhost/wikilogy/mpdata.php?q=maharashtra&id=15',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_16':{
		'hover': 'MANIPUR',
		'url':'http://localhost/wikilogy/mpdata.php?q=manipur&id=16',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_17':{
		'hover': 'MEGHALAYA',
		'url':'http://localhost/wikilogy/mpdata.php?q=meghalaya&id=17',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_18':{
		'hover': 'MIZORAM',
		'url':'http://localhost/wikilogy/mpdata.php?q=mizoram&id=18',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_19':{
		'hover': 'NAGALAND',
		'url':'http://localhost/wikilogy/mpdata.php?q=nagalang&id=19',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_20':{
		'hover': 'ODISHA',
		'url':'http://localhost/wikilogy/mpdata.php?q=odisha&id=20',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_21':{
		'hover': 'PUNJAB',
		'url':'http://localhost/wikilogy/mpdata.php?q=punjab&id=21',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_22':{
		'hover': 'RAJASTHAN',
		'url':'http://localhost/wikilogy/mpdata.php?q=rajasthan&id=22',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_23':{
		'hover': 'SIKKIM',
		'url':'http://localhost/wikilogy/mpdata.php?q=sikkim&id=23',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_24':{
		'hover': 'TAMIL NADU',
		'url':'http://localhost/wikilogy/mpdata.php?q=Tamil_Nadu&id=24',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_25':{
		'hover': 'TELANGANA',
		'url':'http://localhost/wikilogy/mpdata.php?q=telangana&id=25',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_26':{
		'hover': 'TRIPURA',
		'url':'http://localhost/wikilogy/mpdata.php?q=tripura&id=26',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_27':{
		'hover': 'UTTAR PRADESH',
		'url':'http://localhost/wikilogy/mpdata.php?q=lucknow&id=27',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_28':{
		'hover': 'UTTARAKHAND',
		'url':'http://localhost/wikilogy/mpdata.php?q=uttarakhand&id=28',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_29':{
		'hover': 'WEST BENGAL',
		'url':'http://localhost/wikilogy/mpdata.php?q=west%20bengal&id=29',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_30':{
		'hover': 'ANDAMAN AND NICOBAR ISLANDS',
		'url':'http://localhost/wikilogy/mpdata.php?q=andaman%20and%20nicobar%20island&id=30',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_31':{
		'hover': 'CHANDIGARH',
		'url':'http://localhost/wikilogy/mpdata.php?q=chandigarh&id=31',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_32':{
		'hover': 'DADRA AND NAGAR HAVELI',
		'url':'http://localhost/wikilogy/mpdata.php?q=dadra%20and%20nagar%haveli&id=32',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_33':{
		'hover': 'DAMAN AND DIU',
		'url':'http://localhost/wikilogy/mpdata.php?q=daman%20and%20diu&id=33',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_34':{
		'hover': 'LAKSHADWEEP',
		'url':'http://localhost/wikilogy/mpdata.php?q=lakshadweep&id=34',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_35':{
		'hover': 'NATIONAL CAPITAL TERRITORY OF DELHI',
		'url':'http://localhost/wikilogy/mpdata.php?q=national%20capital%20territory%20of%20delhi&id=35',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_36':{
		'hover': 'PUDUCHERRY',
		'url':'http://localhost/wikilogy/mpdata.php?q=puducherry&id=36',
		'target':'new_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	}
}
